class AddInitialSevices < ActiveRecord::Migration
  def change
	Service.create(code: "01", name: "Samoobslužné vracení v době uzavření knihovny (bibliobox)")
	Service.create(code: "02", name: "Půjčování čteček e-knih, tabletů")
	Service.create(code: "03", name: "Půjčování e-knih (e-obsahu)")
	Service.create(code: "04", name: "Půjčování deskových her")
	Service.create(code: "05", name: "Herní konzole přístupné v knihovně")
	Service.create(code: "06", name: "Meziknihovní výpůjční a reprografické služby")
	Service.create(code: "07", name: "Donášková služba pro znevýhodněné občany (handicapované a seniory)")
	Service.create(code: "08", name: "Specializované služby pro zdravotně znevýhodněné (zrakově, sluchově, tělesně, mentálně)")
	Service.create(code: "09", name: "Přístup k online licencovaným zdrojům z knihovny")
	Service.create(code: "10", name: "Rešeršní služby")
	Service.create(code: "11", name: "Wifi")
	Service.create(code: "12", name: "Autentifikace MojeID")
	Service.create(code: "13", name: "Kopírovací a tiskové služby")
	Service.create(code: "14", name: "3D tisk")
	Service.create(code: "15", name: "Dodávání dokumentů (dodávání digitálních kopií článků a částí knih)")
	Service.create(code: "16", name: "Digitalizace dokumentů na přání (pouze dokumenty, které nejsou chráněny autorským právem)")
	Service.create(code: "17", name: "Knihařské služby (laminování, kroužková nebo pevná vazba a související činnosti)")
	Service.create(code: "18", name: "Individuální studijní prostory (včetně možnosti objednání)")
	Service.create(code: "19", name: "Týmová studovna")
	Service.create(code: "20", name: "Noční studovna")
	Service.create(code: "21", name: "Poslechová místa pro hudbu a sledování videa z fondu knihovny")
	Service.create(code: "22", name: "Pronájem prostor (např. učeben, sálů atd.)")
	Service.create(code: "23", name: "Kavárna, bufet")
	Service.create(code: "24", name: "Prostor pro přebalení a nakrmení malých dětí")
	Service.create(code: "25", name: "Parkování pro návštěvníky knihovny")
	Service.create(code: "26", name: "Parkování na speciálních místech pro auta zdravotně handicapovaných návštěvníků knihovny")
  end
end
